name: Build and Upload Artifact

# Triggers the workflow upon pushes to the main branch
on:
  push:
    branches: [ main ]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest  # Workflow will run on an Ubuntu runner

    steps:
      - uses: actions/checkout@v3  # Check out your repository code

      - name: Set up JDK 
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Use Java 17 (adjust as needed)
          distribution: 'temurin'  # Use Temurin distribution

      - name: Build with Gradle
        run: ./gradlew build  # Assume you have a Gradle wrapper

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: LibreLogin  # Name of the artifact
          path: build/libs/*.jar  # Path to the JAR file(s) produced by Gradle 
